hdhomerun_host = "192.168.1.13"
ffmpeg_path = "/opt/boxen/homebrew/bin/ffmpeg"
transcoding_path = "./tmp"
port = "8888"
hd_start = 500

[channel_logos]
506 = "cbs.png"
508 = "abc.png"
511 = "fox.png"
512 = "nbc.png"
